version: "3"
services:
  db:
    image: postgres:13-alpine
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wiki
      POSTGRES_USER: wiki
    restart: unless-stopped
    volumes:
      - /var/volwiki/:/var/lib/postgresql/data
    networks:
      - wiki

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      TZ: America/Sao_Paulo
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wiki
      DB_PASS: wiki
      DB_NAME: wiki
      OFFLINE_ACTIVE: 1
    restart: unless-stopped
    ports:
      - 8080:3000
    networks:
      - wiki

networks:
  wiki:

