version: ”3”
services:

  db:
    image: postgres:11-alpine
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wiki
      POSTGRES_USER: wiki
    logging:
      driver: ”none”
    restart: unless-stopped
    volumes:
      - /var/volwiki/:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      TZ: America/Sao_Paulo
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wiki
      DB_PASS: wiki
      DB_NAME: wiki
      OFFLINE_ACTIVE: 1
    restart: unless-stopped
    volumes:
      - ./sideload:/wiki/data/sideload
      - ./config.yml:/wiki/config.yml
    ports:
      - ”80:3000”
